### ISSUE TITLE
No such file or directory: '/dev/null'

### ISSUE THREAD

**Issue by geo-petrini** [kata198/func_timeout#1]
In Windows there is no '/dev/null' so when a timeout is reached the code throws this exception

func_timeout\StoppableThread.py", line 24, in _stopThread
    self._stderr = open('/dev/null', 'w')
IOError: [Errno 2] No such file or directory: '/dev/null'

**Comment by kata198** [comment]
I've fixed this and released 3.1.0. Tested on windows 7 that it works as expected.
