### ISSUE TITLE
Failed to work in a loop.

### ISSUE THREAD

**Issue by ZQ-Qi** [kata198/func_timeout#17]
Hi, I encountered a trouble when I use func_timeout in a loop.
environment:
- python 3.8
- func-timeout-4.3.5

Here is my code:
`
import func_timeout
 
@func_timeout.func_set_timeout(5)
def ask_choice():
    print("yes or no:")
    return input()
 
while True:
    try:
        s = ask_choice()
    except func_timeout.exceptions.FunctionTimedOut as e:
        s = 'DEFAULT！'
    print(s)
`

Normally, it will simply respond what I input, or respond' DEFAULT!' if I didn't input in 5 second. But as long as I exceed time once, it won't response to my input anymore.
Could you please give me some suggestion? Thank you very much!

**Comment by kata198** [comment]
Func timeout cannot control once in a libc function. In this case, input uses read() from stdin.

What you need to do is use non blocking IO. I actually have a library for this https://github.com/kata198/python-nonblock you can look at how the code works if you don't want to use my lib.
There is a sample game in that library https://github.com/kata198/python-nonblock/blob/master/example/simpleGame.py which you can see for how to use. It waits for input and executes game frames

**Comment by kata198** [comment]
So do lilike

```
startTime = time.time()
endTime = startTime + 5.0
while time.time() < endTime:
    Data = nonblock_read(sys.stdin, 0)
    if not Data:
        time.sleep(.03)
        continue
    processData()
    endTime = time.time() + 5.0

if time.time() >= endTime:
    timeoutOccured()
else:
   Got here by other break of input loop
```

Make sure to setraw and such, read the docs :)
