### ISSUE TITLE
Nested exception in gethostbyname

### ISSUE THREAD

**Issue by glinders** [kata198/func_timeout#20]
If I run:
```
import func_timeout
import time
import socket

print('starting socket.gethostbyname')
try:
    # function gethostbyname normally returns within 40ms (even on VPN); a value
    # of 200ms should be ample and not give a noticeable delay
    if func_timeout.func_timeout(0.2, socket.gethostbyname,
                                 args=('anyname.local',)) == '192.168.1.51':
        print('socket.gethostbyname got a valid name')
except func_timeout.FunctionTimedOut:
    print('socket.gethostbyname timed out')
except Exception as e:
    # handle any exceptions that socket.gethostbyname might raise here
    print('socket.gethostbyname raised exception {}'.format(e))
print('finished socket.gethostbyname')
count = 20
while count > 0:
    time.sleep(1)
    count -= 1
print('finished while')
```
Then `gethostbyname` times out, as intended, but I get a nested exception after around 12 seconds. Output:
```
starting socket.gethostbyname
socket.gethostbyname timed out
finished socket.gethostbyname

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\projects\python\venv3_pyside2\lib\site-packages\func_timeout\dafunc.py", line 68, in funcwrap
    ret.append( func(*args2, **kwargs2) )
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\geert.SALCOM\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\geert.SALCOM\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\projects\python\venv3_pyside2\lib\site-packages\func_timeout\dafunc.py", line 68, in funcwrap
    ret.append( func(*args2, **kwargs2) )
func_timeout.dafunc.FunctionTimedOut-1191607612: Function gethostbyname (args=('anyname.local',)) (kwargs={}) timed out after 0.200000 seconds.

finished while
```
It seems that the background thread that runs `gethostbyname` isn't terminated. It generates exception `socket.gaierror` after it times out and this clashes with `func_timeout` exception `func_timeout.FunctionTimedOut`.

The 'around 12 seconds' is the time `gethostbyname` times out if I run it normally (without `func-timeout`).

**Comment by glinders** [comment]
Example that also shows the threads:

```
import func_timeout
import time
import socket
import threading

print('starting socket.gethostbyname')
try:
    # function gethostbyname normally returns within 40ms (even on VPN); a value
    # of 200ms should be ample and not give a noticeable delay
    if func_timeout.func_timeout(0.2, socket.gethostbyname,
                                 args=('anyname.local',)) == '192.168.1.51':
        print('socket.gethostbyname got a valid name')
except func_timeout.FunctionTimedOut:
    print('socket.gethostbyname timed out')
except Exception as e:
    # handle any exceptions that socket.gethostbyname might raise here
    print('socket.gethostbyname raised exception {}'.format(e))
print('finished socket.gethostbyname')
count = 20
while count > 0:
    time.sleep(1)
    print('Threads: {}'.format([thread.name for thread in threading.enumerate()]))
    count -= 1
print('finished while')
```

**Comment by kata198** [comment]
There is no way to change the instruction pointer while in an external library - python had no cpu control until the C call returns to python, which can then raise the exception.
This is fundamental to the way C and Python work, so libc functions must fully complete before you can stop them. That is why you see the timeout message, a thread is still executing and processing that exception, even though it is scheduled for death. Python2 had a better way of handling this if I recall correctly, but the end result is the same. You can catch that exception in the stack of the message being printed and just return so the thread dies gracefully.

**Comment by glinders** [comment]
As @kata198 suggested, I ended up catching the exception so the thread can die gracefully:

    def check_at_home():
        at_home = False
        # we are at home if a machine with a particular name and IP address is present
        logging.debug('starting socket.gethostbyname')
        try:
            # function gethostbyname normally returns within 40ms (even on VPN); a value
            # of 200ms should be ample and not give a noticeable delay for our customers
            if func_timeout.func_timeout(0.2, socket.gethostbyname,
                                         args=('specific_server.local',)) == '192.168.1.123':
                at_home = True
        except func_timeout.FunctionTimedOut:
            logging.debug('socket.gethostbyname timed out')
        except Exception as e:
            # handle any exceptions that socket.gethostbyname might raise here
            logging.debug('socket.gethostbyname raised exception {}'.format(e))
        logging.debug('self.at_home:{}'.format(at_home))
        return at_home
