### ISSUE TITLE
will it work for windows ?

### ISSUE THREAD

**Issue by Sandy4321** [kata198/func_timeout#21]
will it work for windows ?
https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows

**Comment by mlgtechuser** [comment]
From the [PyPi project description page](https://pypi.org/project/func-timeout/) (at the very bottom):

"Works on windows, linux/unix, cygwin, mac"

**Comment by kata198** [comment]
Yes. It does not use sigalrm.
