### ISSUE TITLE
Library name typo

### ISSUE THREAD

**Issue by mlgtechuser** [kata198/func_timeout#22]
[ver 4.3.5]
There's a typo in the library's Name attribute: installation registers the name as "func-timeout" but the library is still called 'func_timeout'.  See the screenshots below.

![func_timeout](https://user-images.githubusercontent.com/56240329/135778870-cc8f63ea-6f2a-41c0-90c2-fc7f50699e0a.jpg)

**Comment by meitham** [comment]
That's no type.  Pip (or setuptools) canonicalise all underscroes to hyphens, so this is expected.
