### ISSUE TITLE
Way to set thread name?

### ISSUE THREAD

**Issue by csm10495** [kata198/func_timeout#26]
In my app, I have a bunch of threads and tend to set a thread name then use the thread name in the logs. Is there a way to use func_timeout and set the name for the spawned thread (that could be timed-out, if that makes sense)?

In my current logs I see stuff like: 

```
 Thread-39 (funcwrap)
```
as the thread id, which isn't as easy to look at as if I could give that spawned thread a name. 

Threads have names that can be accessed/set via `<thread>.name` .. also via the constructor's name kwarg.

Thanks!

**Comment by kata198** [comment]
Yes.

It's not in the default constructor, because it would be the same name for every call to that function, which only works if a @func_timeout function is only being called once.

What you can do is set the thread name to something meaningful at the start of the function, like this:

```
@func_set_timeout(1)
def func_2(sec):
    threading.current_thread().setName('MyThreadName')
    sleep(sec)
    doStuff(sec)
```
