### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by yogeshyadav2710** [kata198/func_timeout#31]
Hi, 

We are planning to use the library
licensed under GNU Library General Public License v2
we are not doing any modifications in the source code of the library
GPL, or our application can be made proprietary
can you please more insights into this

**Comment by kata198** [comment]
Yes, you can include and use the project, but you cannot modify it.

If you modify the library yourself, you must make those changes publicly available. The easiest way to do this is to submit your changes back to the project. It doesn't matter if I accept them.

Thanks, and enjoy the project!
