### ISSUE TITLE
FunctionTimedOut Exception cannot be caught with Exception

### ISSUE THREAD

**Issue by GrimzEcho** [kata198/func_timeout#5]
func_timeout.exceptions.FunctionTimedOut does not inherit from `Exception`, making it impossible to catch in general purpose try/except blocks.

Python Version: 2.7
Windows 10

#### Minimal Example:
```python
def catch_specific():
    try:
        raise FunctionTimedOut('foo')
    except FunctionTimedOut as e:
        print('handled ' + str(e))

def catch_general():
    try:
        raise FunctionTimedOut('bar')
    except Exception as e:
        print('handled ' + str(e))

if __name__ == '__main__':
    print(issubclass(FunctionTimedOut, Exception))
    catch_specific()
    catch_general()
```

#### Expected output when calling `catch_general()`
`> handled bar`

#### Actual output when calling `catch_general()`
```
Traceback (most recent call last):
  File "C:/Users/...", line 31, in <module>
    catch_general()
  File "C:/Users/.../scratch_3.py", line 21, in catch_general
    raise FunctionTimedOut('bar')
func_timeout.exceptions.FunctionTimedOut: bar
```

#### Why does this matter
While `except Exception` is generally a bad practice, there are various scenarios where it is the correct choice. The difference between `except Exception:`, and a naked `except:` or `except BaseException:` is that the latter two catch SystemExit, KeyboardInterrupt and a few other exceptions that should always be re-raised. Where `except Exception` is used for things like loggers, web servers, remote terminals, etc, where you want to log the exception and resume program execution.

**Comment by kata198** [comment]
This is also  intentional, and is described in both the README, the pydocs, and the docstrings.

This is so that it is able to break out of blocks like the following:

    try:
        doSomething()
    except Exception as e:
        handleException

You CAN catch this exception by either using a blank except handler, or catching "BaseException" instead, but this will break the ability for it to actually time out the function unless you set the "raiseEvery" parameter to a low enough number that it hits whilst within the BaseException exception handler.

If you intend to have cleanup code that exits cleanly, this is perfectly acceptable, and can be accomplished like so:

    try:
        doSomethingThatMightTimeout()
    
    except BaseException as e:
        if issubclass(e.__class__, FunctionTimedOut):
             doCleanup()
             return
        else:
             normalExceptionHandler()

**Comment by kata198** [comment]
I'm going to close this, as it appears to be a misunderstanding of the documentation. If you are having further issues, feel free to open another issue and I will assist.

**Comment by kata198** [comment]
You can also directly catch the FunctionTimedOut exception, which is probably a better choice than BaseException.

**Comment by GrimzEcho** [comment]
Yes, this makes sense, and thank you for taking the time to respond. 

We have places in our code where we do:
```
try:
    # lots of complex code with various inner try/catch blocks
    try:
        someFunctionThatShouldTimeout()
    except FunctionTimedOut as e:
        # cleanup   
except
    # log, but don't exit
```

e.g. use a bare except to catch anything that somehow slipped by other exception blocks.

Would this explain why someFunctionThatShouldTimeout() isn't exiting when the timeout is triggered? The code in the except FunctionTimedOut block gets triggered, but the thread running `someFunction` doesn't terminate.

**Comment by zachliu** [comment]
sorry to comment on an old closed issue :sweat_smile: 
just want to point out that if you raise a `FunctionTimedOut` in a multiprocessing `Pool`, it will leave the sub-process dead and the parent process will hang forever. my guess is `Pool` doesn't know how to deal with `BaseException`
